top_level_config:
  root: demo/data
  units_to_set:
    raw_sample: [0.00003333333333333333, s, rs]
    lfp_sample: [0.002, s, ls]

subjects_config:
  _base:
    sessions:
      - session_1

  control:
    inherits: _base
    members: [animal_1, animal_2, animal_3]

  drug:
    inherits: _base
    members: [animal_4, animal_5, animal_6]

sessions_config:
  session_1:
    label: session_1
    start: 0
    duration: 60
    data_sources:
      - lfp
      - spikes
    epochs:
      - tone
      - pretone

data_sources_config:
  lfp:
    registry_key: lfp
    label: lfp
    path: "{experiment.root}/{subject.id}_lfp.npy"
    file_ext: npy
    sampling_rate: 500
    row_to_region:
      0: bla

  spikes:
    registry_key: spike
    label: spikes
    path: "{experiment.root}/{subject.id}_spikes.npz"
    file_ext: npz
    sampling_rate: 30000

data_identity_config:
  neuron:
    source: spike
    match: null

  lfp_brain_region:
    source: lfp
    match: region

epochs_config:
  tone: 
    epoch_kind: tone
    events: [pip]
    onsets: [10, 20, 30, 40, 50]
    duration: 5
    units: s
    conditions:
      stimulus: tone


  pretone:
    relative_to: tone
    epoch_kind: pretone
    shift: -5
    duration: 5
    units: s
    conditions:
      stimulus: pretone


events_config:
  pip:
    spacing: 1
