import numpy as np
import xarray as xr
from collections.abc import Iterable
from copy import deepcopy

from ..transformers.transformer_mixins import (
    CalculateMixin,
    UnstackMixin,
    IntersectionMixin,
)
from k_onda.transformers import SelectMixin
from k_onda.graph.traversal import build_generations, list_nodes, new_tree
from k_onda.central.registry import type_registry


@type_registry.register
class Signal(CalculateMixin, SelectMixin, IntersectionMixin):
    """A signal is an immutable node in the execution graph. A signal can be generated by calling 
    `DataComponent.to_signal` or by passing a signal or signals through a `Transformer`.  Before 
    execution, a signal's `data_schema` tracks the shape of its associated data. Accessing a leaf 
    signal's `data` property will trigger recursive execution, so that data is fetched from the 
    origin `DataComponent`, operated on by `Transfomer`s, and eventually returned."""
    # strategy is one of: "lazy", "memory", "disk"
    def __init__(
        self,
        inputs,
        *,
        transform=None,
        data_schema=None,
        transformer=None,
        key_spec=None,
        context=None,
        origin=None,
        start=None,
        duration=None,
        source_signal=None,
        storage_strategy="lazy",
        conditions=None,
        last_stack_index = None,
        apply_kwargs = None
    ):
        self._inputs = inputs if isinstance(inputs, Iterable) else (inputs,)
        self._transform = transform
        self.transformer = transformer
        self.key_spec = key_spec
        self._data_schema = data_schema
        self.context = context
        self.origin = origin
        self.start = start or getattr(self.parent, "start", None)
        self.duration = duration or getattr(self.parent, "duration", None)
        self.source_signal = source_signal
        self._storage_strategy = storage_strategy
        self._cache = None
        self.conditions = conditions or {}
        self.last_stack_index = last_stack_index 
        if self.last_stack_index is None and self.inputs:
            self.last_stack_index = getattr(self.inputs[0], 'last_stack_index', None)
        self._validate()
        self._is_compiled = False
        self.apply_kwargs = apply_kwargs
    

    @property
    def inputs(self):
        return self._inputs

    @inputs.setter
    def inputs(self, value):
        self._inputs = value
        self._data_schema = None

    @property
    def data(self):
        return self._materialize()

    @property
    def data_schema(self):
        if self._data_schema is None:
            self._data_schema = self.transformer.make_output_schema(
                self.inputs[0].data_schema, key_spec=self.key_spec
            )
        return self._data_schema
    
    @property
    def transform(self):
        if self._transform is None:
            self._transform = self.transformer.build_transform_for(self)
        return self._transform

    @property
    def parent(self):
        return self.inputs[0] if len(self.inputs) == 1 else None

    @property
    def origin(self):
        if hasattr(self, "_origin") and self._origin is not None:
            return self._origin
        self._origin = getattr(self.parent, "origin", None)
        return self._origin

    @origin.setter
    def origin(self, value):
        self._origin = value

    @property
    def is_source(self):
        return not getattr(self, "inputs", None)

    @property
    def generations(self):
        return build_generations(self)

    @property
    def transform_history(self):
        def func(node, _):
            return getattr(node, "transformer", None)

        return build_generations(self, func)

    def compile(self, memo=None):
        memo = {} if memo is None else memo
        leaf = new_tree(self, memo=memo)
        plan = leaf.plan_on_signal()
        for node in list_nodes(plan):
            node._is_compiled = True
        return plan
    
    def rebuild_with_inputs(self, rebuilt_inputs):

        return type(self)(
            inputs=tuple(rebuilt_inputs), 
            transformer=self.transformer,
            key_spec=self.key_spec,
            data_schema=None,
            transform=None,
            context=self.context,
            origin=self.origin,
            start=self.start,
            duration=self.duration,
            source_signal=self.source_signal,
            storage_strategy=self._storage_strategy,
            conditions=self.conditions,
            last_stack_index=self.last_stack_index,
            apply_kwargs=self.apply_kwargs
            )

    def _validate(self):
        if not self.is_source:
            if self._transform is None and self.transformer is None:
                raise ValueError("A non-source Signal needs either a concrete " \
                "transform or a transformer recipe.")
        return True

    def __add__(self, other):
        return self.add(other)

    def __sub__(self, other):
        return self.subtract(other)

    def __mul__(self, other):
        return self.multiply_by(other)

    def __truediv__(self, other):
        return self.divide_by(other)

    def __deepcopy__(self, memo):
        
        cls = type(self)
        copied = cls.__new__(cls)
        memo[id(self)] = copied

        copied.inputs = tuple(deepcopy(inp, memo) for inp in self.inputs)
        copied._transform = self._transform
        copied.key_spec = self.key_spec
        copied.transformer = self.transformer
        if self.is_source:
            copied._transform = self._transform
            copied._data_schema = deepcopy(self._data_schema, memo)
        else:
            copied._transform = None
            copied._data_schema = None
        copied.last_stack_index = self.last_stack_index
        copied.context = self.context
        copied.origin = self.origin
        copied.start = self.start
        copied.duration = self.duration
        copied.source_signal = self.source_signal
        copied._storage_strategy = self._storage_strategy
        copied._cache = None
        copied.conditions = deepcopy(self.conditions, memo)
        copied._is_compiled = self._is_compiled
        copied.apply_kwargs = deepcopy(self.apply_kwargs, memo)

        return copied

    def _materialize(self):
        if not self._is_compiled:
            raise ValueError(
                "You must call .compile() on a signal before accessing"
                "the .data property."
            )
        if self._cache is None:
            input_data = [input.data for input in self.inputs]
            self._cache = self.transform(*input_data)
        return self._cache

    @property
    def endpoints(self):
        return {
            dim: (self.data.coords[dim][0], self.data.coords[dim][-1])
            for dim in self.data
        }

    @property
    def data_identity(self):
        # TODO: architectural debt. Threading data_identity through the origin
        # chain means deepcopying any signal drags the entire entity graph along,
        # causing hash failures on partially-constructed DataIdentity objects
        # (deepcopy uses __new__, not __init__). Short-term fix: add __deepcopy__
        # to DataIdentity to return self. Long-term fix: store data_identity_id
        # (uid) on the root signal and resolve it via a registry, so signals can
        # still belong to a DataIdentity without holding a live reference.
        if type(self.origin) in [tuple, list]:
            origin = None
            for entity in self.origin:
                if entity is not None:
                    origin = entity
                    break
        else:
            origin = self.origin

        return getattr(origin, "data_identity", None)

    def output_class_for_selection(self):
        pass


@type_registry.register
class TimeSeriesSignal(Signal):
    dim_defaults = {"time": "s"}

    def __init__(self, inputs, *, sampling_rate=None, **kwargs):
        super().__init__(inputs, **kwargs)
        self.sampling_rate = sampling_rate or self._sampling_rate_from_context()

    def _sampling_rate_from_context(self):
        origin = self.origin
        if isinstance(origin, tuple):
            origin = next((o for o in origin if o is not None), None)
        return getattr(origin, "sampling_rate", None)


@type_registry.register
class TimeFrequencySignal(TimeSeriesSignal, CalculateMixin, SelectMixin):
    dim_defaults = {"time": "s", "frequency": "Hz"}


@type_registry.register
class ScalarSignal(Signal):
    pass


@type_registry.register
class DatasetSignal(Signal):
    def __init__(self, inputs, **kwargs):
        super().__init__(inputs, **kwargs)

    def __getitem__(self, key):
        return self.payload(key)

    def payload(self, key):
        def transform(data):
            if not isinstance(data, (xr.Dataset, dict)):
                raise TypeError("`data` must be a dictionary or xarray Dataset")
            return data[key]

        # TODO: I'm not sure that payload should be the same type for the DatasetSingals
        # For PointProcessSignal, yes.  Need to think about this.

        return type(self)(
            inputs=(self,),
            transform=transform,
            origin=self.origin,
            transformer=None,
            data_schema=self.data_schema[key],
        )


@type_registry.register
class PointProcessSignal(Signal):
    def __init__(self, inputs, *, sampling_rate=None, **kwargs):
        super().__init__(inputs, **kwargs)

        self.sampling_rate = sampling_rate or getattr(
            self.parent, "sampling_rate", None
        )

    def to_binary(self):
        if self.sampling_rate is None:
            raise ValueError("can't expand signal to binary without sampling_rate")
        return BinarySignal((self,), sampling_rate=self.sampling_rate)

    @property
    def neuron(self):
        # Convenience accessor for neuron-backed PointProcessSignals.
        from ..sources.spike_sources import Neuron

        if isinstance(self.data_identity, Neuron):
            return self.data_identity
        return None


@type_registry.register
class DistributionSignal(Signal):
    pass


@type_registry.register
class BinarySignal(Signal):
    # stored as boolean array at some sampling rate
    # supports & | ~

    def __init__(
        self,
        inputs,
        *,
        sampling_rate=None,
        intervals=None,
        **kwargs,
    ):
        super().__init__(inputs, **kwargs)

        self.intervals = intervals
        self.sampling_rate = sampling_rate or getattr(
            self.parent, "sampling_rate", None
        )

    def __and__(self, other):
        return self.intersection(other)

    def __rand__(self, other):
        # called when: non_mask & mask
        return other.apply_mask(self)

    @property
    def data(self):
        if self.intervals:
            return self._bool_train_from_intervals()
        return self._materialize()

    def _bool_train_from_intervals(self):
        length = (
            self.duration
            or (self.endpoints[1] - self.endpoints[0]) / self.sampling_rate
        )
        arr = np.full(length, False)

        for start, end in self.intervals:
            arr[slice(start, end)] = True

        return arr





@type_registry.register
class ValidityMask(BinarySignal):
    pass

@type_registry.register
class SignalStack(CalculateMixin, UnstackMixin):
    def __init__(
        self,
        inputs,
        transformer,
        transform=None,
        data_schema=None,
        signal_class=None,
        key_spec=None,
        apply_kwargs=None
    ):
        if isinstance(inputs, type_registry.Collection):
            self.collection = inputs
            self.signals = tuple(inputs.signals)
            self.inputs = self.signals
        
        elif len(inputs) == 1 and getattr(inputs[0], "is_stack", False):
            parent_stack = inputs[0]
            self.collection = getattr(parent_stack, "collection")
            self.signals = parent_stack.signals
            self.inputs = tuple(inputs)

        elif all(isinstance(inp, type_registry.Signal) for inp in inputs):
            self.collection = None
            self.signals = tuple(inputs)
            self.inputs = tuple(inputs)

        else:
            raise ValueError("SignalStack inputs must be a Collection, parent stack, or signals.")
       
        self._data_schema = data_schema
        self._transform = transform
        self.transformer = transformer
        self._cache = None
        self.signal_class = signal_class or type(self.signals[0])
        self.is_stack = True
        self._is_compiled = False
        self.key_spec = key_spec
        self.apply_kwargs = apply_kwargs

   

    @property
    def transform(self):
        if self._transform is None:
            self._transform = self.transformer.build_transform_for(self)
        return self._transform

    def rebuild_with_inputs(self, rebuilt_inputs):
        return type(self)(
            inputs=rebuilt_inputs, 
            transform=None,
            key_spec=self.key_spec,
            transformer=self.transformer,
            data_schema=None,
            signal_class=self.signal_class,
            apply_kwargs=self.apply_kwargs
            )

    def compile(self):
        # TODO: What this should eventually do is find the constituent signals, call compile on them
        # and rewrite the graph.
        raise NotImplementedError(
            "SignalStack cannot currently be compiled as a terminal node. "
            "Compile a downstream signal or unstack before materialization."
        )

    def _materialize(self):
        if not self._is_compiled:
            raise NotImplementedError(
                "SignalStack cannot currently be compiled as a terminal node. "
                "Compile a downstream signal or unstack before materialization."
            )

        if self._cache is None:
            input_data = [inp.data for inp in self.inputs]
            self._cache = self.transform(*input_data)
        return self._cache

    @property
    def parent(self):
        if len(self.inputs) == 1 and getattr(self.inputs[0], "is_stack", False):
            return self.inputs[0]
        else:
            return self.collection
       
        

    @property
    def data(self):
        return self._materialize()

    @property
    def data_schema(self):
        if self._data_schema is None:
            self._data_schema = self.transformer.make_output_schema(
                self.inputs[0].data_schema, key_spec=self.key_spec
            )
        return self._data_schema

    def group_by(self):
        # Placeholder for future API.
        pass


@type_registry.register
class CollectionInputSignal(Signal):
    def __init__(self, inputs, **kwargs):
        if isinstance(inputs, type_registry.Collection):
            self.collection = inputs
            inputs = tuple(inputs.signals)
        else:
            self.collection = None

        super().__init__(inputs, **kwargs)

    def _materialize(self):
        if not self._is_compiled:
            raise ValueError(
                "You must call .compile() on a signal before accessing"
                "the .data property."
            )
        if self._cache is None:
            input_data = [inp.data for inp in self.inputs]
            self._cache = self.transform(*input_data)
        return self._cache



@type_registry.register
class AggregatedSignal(CollectionInputSignal):
    pass


@type_registry.register
class IndexedSignal(CollectionInputSignal):

    def kmeans(self, n_clusters=8, **kwargs):
        from k_onda.transformers import KMeans

        return KMeans(n_clusters=n_clusters, **kwargs)(self)

    def classify(self, label_name, label_spec=None, label_func=None):
        from k_onda.sinks import Classify

        node = self.compile()
        chain = []
        while isinstance(node, IndexedSignal):
            chain.append(node)
            node = node.inputs[0] if node.inputs else None

        return Classify(label_name, label_spec=label_spec, label_func=label_func)(
            *chain
        )


@type_registry.register
class SelectorSignal(Signal):
    def __init__(self, inputs, **kwargs):
        super().__init__(inputs, **kwargs)

    @property
    def output_class(self):
        return getattr(self.inputs[0], "output_class", type(self.inputs[0]))
