name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install third-party dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt -r requirements.txt

    - name: Install project (editable)
      run: pip install -e .

    - name: Run tests and notebook
      run: |
        pytest --nbval-lax demo/k_onda_demo.ipynb
        pytest --cov=k_onda --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}